version: "3.8"
services:
  ligos:
    container_name: ligos_prod
    build: .
    image: ligos_prod
    restart: always
    networks:
      - ligos
    ports:
      - "3000:3000"
    env_file: .env.local
    environment:
      - NODE_ENV=production

networks:
  ligos:
    driver: bridge
